

export default {
    MONGODB_CONNECTION: process.env.MONGODB_CONNECTION,
    KAFKA_CONNECTION: process.env.KAFKA_CONNECTION,
    KAFKA_TOPIC_LISTEN: process.env.KAFKA_TOPIC_LISTEN,
    KAFKA_TOPIC_SEND: process.env.KAFKA_TOPIC_SEND,
    BITCOIN_NODE_HOST: process.env.BITCOIN_NODE_HOST,
    BITCOIN_NODE_PORT: process.env.BITCOIN_NODE_PORT,
    BITCOIN_NODE_RPC_USERNAME: process.env.BITCOIN_NODE_RPC_USERNAME,
    BITCOIN_NODE_RPC_PASSWORD: process.env.BITCOIN_NODE_RPC_PASSWORD,
    BITCOIN_ZERO_MQ_PORT: process.env.BITCOIN_ZERO_MQ_PORT,
    BITCOIN_SYNC_START_BLOCK: process.env.BITCOIN_SYNC_START_BLOCK,
}